### ISSUE TITLE
Two chained selects on same site.

### ISSUE THREAD

**Issue by NiTRoeSE** [smarek/jquery-chained-selects#1]
Hi, thanks for this nice plugin.

I use it in 1 page successful and it works.
Now have have the need to have a second chained select on the same site.
This basically works but if i select something in first dropdown , values changes in second dropdown.
I use it with "onselectedCallback" option but this didn't help.

Is there any way to have 2 instances of this script in same site which don't affect each other ?

first function contains:

```js
function spartakus_school_choice(){
  $('#school_data').chainedSelects({
                              data: schoolData,
                              loggingEnabled: false,
                              selectCssClass: "form-select selectpicker",
  
                              onSelectedCallback: function (spartakus_school_object) {
                                  if (console !== undefined) {
                                      console.log("selected spartakus school object:", spartakus_school_object);
                                      }
                                  document.getElementById("school_building_wrapper").innerHTML = `
                                      <input class="alert alert-success" style="padding: 0.4rem 0.4rem;"type="text" id="spartakus_building" name="spartakus_building" value=${spartakus_school_object} data-enpassusermodified="no" readonly>
                                  `;
  
                              },
                          });
}
```
second function contains:

```js
function spartakus_room_choice(){
   $('#spartakus_data').chainedSelects({
                              data: sData,
                              loggingEnabled: false,
                              selectCssClass: "form-select selectpicker",
  
                              onSelectedCallback: function (spartakus_room_id) {
                                  if (console !== undefined) {
                                      console.log("selected spartakus roomID:", spartakus_room_id);
                                      }
                                  document.getElementById("spartakus_room_id_wrapper").innerHTML = `
                                      <input class="alert alert-success" style="padding: 0.4rem 0.4rem;"type="text" id="spartakus_roomid" name="spartakus_roomid" value=${spartakus_room_id} data-enpassusermodified="no" readonly>
                                  `;
  
                              },
                          });

}
```

Thanks in advanced!

**Comment by smarek** [comment]
Hey sure, plugin contains data within single select element, so having
multiple of those should not yield conflict. Are you sure you use different
ids and callback for the two instancea you create? Can you extend my
showcase/demo and add a second set of data so we have minimal reproduction
code please?

Dne út 12. 9. 2023 14:52 uživatel NiTRoeSE ***@***.***>
napsal:

**Comment by NiTRoeSE** [comment]
> 

Yes i can try it.
i write the value given in each callback in a input field in html.
The selection part is fine, but if i select something in first dropdown than the value in second dropdown changes.
Its seems also to me that the ids are equal but that's not the case, i have checked it multiple times.

Its seems to me related to randomness which callback is loaded or active last and this always gets the value no matter in which dropdown you select.

Thanks in advanced & kind regards

**Comment by smarek** [comment]
Well damn me, seems like you were right all along, I created demo_multiple.html to demonstrate and found single issue with options cross-contaminating between instances. Please check the current version on master branch and this demo https://smarek.github.io/jquery-chained-selects/demo_multiple.html

I will release 2.1.1 to npm after we close this issue, thank you

**Comment by NiTRoeSE** [comment]
> Well damn me, seems like you were right all along, I created demo_multiple.html to demonstrate and found single issue with options cross-contaminating between instances. Please check the current version on master branch and this demo https://smarek.github.io/jquery-chained-selects/demo_multiple.html
> 
> I will release 2.1.1 to npm after we close this issue, thank you

Nice, it works :D
I´m happy that the idea point you to the right direction.
Thanks for your fast support and the work on this nice script!

Kind regards
